### ISSUE TITLE
huggingface_hub.utils._errors.LocalEntryNotFoundError

### ISSUE THREAD

**Issue by sascharo** [cantrell/stable-diffusion-api-server#22]
Any idea how to resolve these errors?

```
(sd-api-server) PS A:\bc\source\repos\stable-diffusion-api-server> python server.py
Traceback (most recent call last):
  File "B:\home\anaconda3\envs\sd-api-server\lib\site-packages\diffusers\configuration_utils.py", line 324, in load_config
    config_file = hf_hub_download(
  File "B:\home\anaconda3\envs\sd-api-server\lib\site-packages\huggingface_hub\utils\_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "B:\home\anaconda3\envs\sd-api-server\lib\site-packages\huggingface_hub\file_download.py", line 1169, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server.py", line 131, in <module>
    manager.add_engine( 'txt2img', EngineStableDiffusion( diffusers.StableDiffusionPipeline,        sibling=None ) )
  File "server.py", line 62, in __init__
    self.engine = pipe.from_pretrained( 'runwayml/stable-diffusion-v1-5', use_auth_token=hf_token.strip() )
  File "B:\home\anaconda3\envs\sd-api-server\lib\site-packages\diffusers\pipeline_utils.py", line 446, in from_pretrained
    config_dict = cls.load_config(
  File "B:\home\anaconda3\envs\sd-api-server\lib\site-packages\diffusers\configuration_utils.py", line 352, in load_config
    raise EnvironmentError(
OSError: runwayml/stable-diffusion-v1-5 does not appear to have a file named model_index.json.
```

**Comment by sascharo** [comment]
I created another environment from scratch and installed all the packages with conda instead of pip, and the downloads work now.
